controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_endeffector_controller
    joints:
      - joint_5